### ISSUE TITLE
KeyError: 'BTC'

### ISSUE THREAD

**Issue by seregasoft** [alighazi/price_alert_bot#1]
Hello. Several days it worked ok, but now:
```
opened cache db: 4 entries
2021-01-20 18:38:23.126379 Getting updates…
processing 550262006...
2021-01-20 18:38:23.249873 - handling command "chart BTC"...
cache expired for key: {key}
generating chart for BTC USD
requesting: https://api.binance.com/api/v1/klines - symbol=BTCUSDT&interval=1h&limit=170
loading symbols from network: https://min-api.cryptocompare.com/data/top/totalvol?limit=100&tsym=USD&page=0
loading symbols from network: https://min-api.cryptocompare.com/data/top/totalvol?limit=100&tsym=USD&page=1
loading symbols from network: https://min-api.cryptocompare.com/data/top/totalvol?limit=100&tsym=USD&page=2
loading symbols from network: https://min-api.cryptocompare.com/data/top/totalvol?limit=100&tsym=USD&page=3
loading symbols from network: https://min-api.cryptocompare.com/data/top/totalvol?limit=100&tsym=USD&page=4
loading symbols from network: https://min-api.cryptocompare.com/data/top/totalvol?limit=100&tsym=USD&page=5
loading symbols from network: https://min-api.cryptocompare.com/data/top/totalvol?limit=100&tsym=USD&page=6
loading symbols from network: https://min-api.cryptocompare.com/data/top/totalvol?limit=100&tsym=USD&page=7
loading symbols from network: https://min-api.cryptocompare.com/data/top/totalvol?limit=100&tsym=USD&page=8
loading symbols from network: https://min-api.cryptocompare.com/data/top/totalvol?limit=100&tsym=USD&page=9
index: 1, partition: 0, fsym: BTC, tsym: USD
Traceback (most recent call last):
  File "/usr/home/serega/price_alert2/price_alert_bot/tg_bot.py", line 266, in processUpdates
    self.processMessage(message)
  File "/usr/home/serega/price_alert2/price_alert_bot/tg_bot.py", line 210, in processMessage
    self.handleBotCommand(message)
  File "/usr/home/serega/price_alert2/price_alert_bot/tg_bot.py", line 151, in handleBotCommand
    price = self.get_price(fsym, tsym)
  File "/usr/home/serega/price_alert2/price_alert_bot/tg_bot.py", line 47, in get_price
    return self.repository.get_price(fsym, tsym)
  File "/usr/home/serega/price_alert2/price_alert_bot/repository/market.py", line 61, in get_price
    return self.price_partitions[partition][fsym][tsym]
KeyError: 'BTC'
```

**Comment by seregasoft** [comment]
logger_config DEBUG: price pair not valid BTC USD
logger_config INFO: handling command "p"...
logger_config DEBUG: sending msg to 111111111 'Invalid symbols BTC USD'
logger_config INFO: handling command "p btc"...
logger_config DEBUG: sending msg to 111111111 'Invalid symbols BTC USD'
logger_config INFO: handling command "p btc usd"...
logger_config DEBUG: sending msg to 111111111 'Invalid symbols BTC USD'
logger_config INFO: handling command "p btc eth"...
logger_config DEBUG: sending msg to 111111111 'Invalid symbols BTC ETH'

**Comment by alighazi** [comment]
It should be the problem with cryptocompare api which rate limits us. I
need to add a proper request throttling mechanism, probably using a library.

**Comment by Banila48** [comment]
Same I have this issue of encountering "KeyError" after a few days. I am also trying to figure out how to throttle so that the unknown cryptocompare rate limit is not hit

**Comment by Banila48** [comment]
So far seems to be good 

I am using the ratelimit library from [here](https://pypi.org/project/ratelimit/)

I reduce my calls to 2/3 times per minute

Will keep monitoring and report if my AWS bot is down

**Comment by Banila48** [comment]
After almost 7 days, the bot died, "KeyError: 'LINK'"

I will figure a way to let it last longer this time

**Comment by hrdkgtm** [comment]
I have been experiencing the same problem.

I think the problem is because the get_price function is not making a request with an api key header like get_symbols

https://github.com/alighazi/price_alert_bot/blob/master/api/cryptocompare.py#L35

I have implemented the change in my forked repo + rate limiting as suggested by @Banila48 , will monitor it and see if the bot survive

**Comment by alighazi** [comment]
the bot is back up 
for further help or discussions please use https://t.me/alertbotgang
