### ISSUE TITLE
bot seems to be down

### ISSUE THREAD

**Issue by Guofeng-Tang** [alighazi/price_alert_bot#3]
no reaction from bot after typing in a few commands

![image](https://user-images.githubusercontent.com/25407436/113279121-5683b300-9315-11eb-8e3d-fe713905059b.png)

**Comment by cypherpunk1984** [comment]
Yeah it is down for me too.
Such a shame, was a good bot.

**Comment by alighazi** [comment]
the bot is back up 
for further help or discussion please use https://t.me/alertbotgang
