### ISSUE TITLE
Self-hosting instructions please?

### ISSUE THREAD

**Issue by cypherpunk1984** [alighazi/price_alert_bot#4]
Hi dev.
Since the bot is down, probably because of API abuse or something like that.
Could you put the instructions to self-host it, so I can install it on my own personal server and register a personal API from the source service you are using?
That would be awesome.

**Comment by Banila48** [comment]
I tried hosting it and it is down after working for a few days as well. I followed this tutorial and hosted the bot on Amazon EC2

**Comment by cypherpunk1984** [comment]
> I tried hosting it and it is down after working for a few days as well. I followed this tutorial and hosted the bot on Amazon EC2

What tutorial? Can you link it to me please?

**Comment by Banila48** [comment]
https://www.youtube.com/watch?v=MApTRT37B0k

**Comment by desertkun** [comment]
1. Clone this repo
2. Create secrets.py with following contents:
```
TG_TOKEN = "..."
CC_API_KEY = "..."
```
3. Build your docker image like so
```Dockerfile
FROM python:3-buster
COPY . /app
RUN mkdir /log
WORKDIR /app
RUN pip install -r /app/requirements.txt
CMD ["python3", "/app/tg_bot_service.py"]
```

**Comment by cypherpunk1984** [comment]
> 1. Clone this repo
> 2. Create secrets.py with following contents:
> 
> ```
> TG_TOKEN = "..."
> CC_API_KEY = "..."
> ```
> 
> 1. Build your docker image like so
> 
> ```dockerfile
> FROM python:3-buster
> COPY . /app
> RUN mkdir /log
> WORKDIR /app
> RUN pip install -r /app/requirements.txt
> CMD ["python3", "/app/tg_bot_service.py"]
> ```

Thank you for that.
But I only have a 1gb ram 1 core ubuntu 20 VPS, so I can't use docker on it (docker needs at least 2gb ram).
Would you be so kind to instruct me how to do it the normal way, no docker involved?
Thanks in advance.

**Comment by Banila48** [comment]
> > 1. Clone this repo
> > 2. Create secrets.py with following contents:
> > 
> > ```
> > TG_TOKEN = "..."
> > CC_API_KEY = "..."
> > ```
> > 
> > 
> > 
> > 1. Build your docker image like so
> > 
> > ```dockerfile
> > FROM python:3-buster
> > COPY . /app
> > RUN mkdir /log
> > WORKDIR /app
> > RUN pip install -r /app/requirements.txt
> > CMD ["python3", "/app/tg_bot_service.py"]
> > ```
> 
> Thank you for that.
> But I only have a 1gb ram 1 core ubuntu 20 VPS, so I can't use docker on it (docker needs at least 2gb ram).
> Would you be so kind to instruct me how to do it the normal way, no docker involved?
> Thanks in advance.


You can just follow the youtube tutorial and use AWS EC2 to hosrt your bot. It is free for 1 year and CryptoCompare API has enough calls, lifetime 250,000. Can always create dummy accounts to refresh your API calls if you need

Just take note that CryptoCompare has a API Rate Limit, so you will want to add a throttle function before each api call function

**Comment by Banila48** [comment]
import sys, math, time, requests, pickle
from datetime import datetime
import collections
import config
import time
import requests
from urllib3.util.retry import Retry
from requests.adapters import HTTPAdapter
from ratelimit import limits, sleep_and_retry


BASE_URL = "https://min-api.cryptocompare.com"



class CryptoCompare():
    def __init__(self):
        self.session = requests.Session()
        retries = Retry(total=2,
                        backoff_factor=0.1,
                        status_forcelist=[ 500, 502, 503, 504 ])

        self.session.mount(BASE_URL, HTTPAdapter(max_retries=retries))
        
    # 2 calls per minute
    CALLS = 2
    RATE_LIMIT = 60
    @sleep_and_retry
    @limits(calls=CALLS, period=RATE_LIMIT)   
    def get_symbols(self):
        syms = collections.OrderedDict()
        for page in range(0,10):        # Increase page rank to get more coins
            url = f"{BASE_URL}/data/top/totalvol?limit=100&tsym=USD&page={page}"
            print(f'loading symbols from network: {url}')
            time.sleep(0.3)
            r = self.session.get(url, headers={"authorization": "Apikey "+config.CC_API_KEY})
            data = r.json()["Data"]
            for coin in data:
                syms[coin["CoinInfo"]["Internal"]] = coin["CoinInfo"]["FullName"]
        return syms
    
    # 3 calls per minute
    CALLS = 3
    RATE_LIMIT = 60
    @sleep_and_retry
    @limits(calls=CALLS, period=RATE_LIMIT)   
    def get_price(self, fsyms, tsyms):
        url = f"{BASE_URL}/data/pricemulti?fsyms={','.join(fsyms)}&tsyms={','.join(tsyms)}"
        r = self.session.get(url)
        return r.json()

    #max count is 30
    def get_top(self, tsym= "USD", count=100): #original is 40 top coins
        url = f"{BASE_URL}/data/top/mktcapfull?limit={count}&tsym={tsym}"
        r = self.session.get(url)
        data= r.json()["Data"]
        coins =[]
        rank=1
        for row in data:
            coin={}
            coin["rank"]= rank
            rank+=1
            coin["cap"]= row["RAW"][tsym]["MKTCAP"]
            coin["symbol"]=row["CoinInfo"]["Name"]
            coin["price"]=row["DISPLAY"][tsym]["PRICE"]
            
            coins.append(coin)

        return coins

> I am using this [ratelimit library](https://pypi.org/project/ratelimit/)

**Comment by alighazi** [comment]
thanks for the patch. however I just removed the dependency on cryptocompare. since their free tier is really not sufficient for our usage. all the data is fetched from binance now. and no trotling is needed anymore either.

**Comment by alighazi** [comment]
for further disscussion please join the telegram group https://t.me/alertbotgang

**Comment by imkind1** [comment]
i have error when run docker ...

docker: Error response from daemon: pull access denied for web_server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
